CREATE TABLE PROJECT(
  NAME VARCHAR(50) PRIMARY KEY,
  FOLDER VARCHAR(300),
  SWARM_TOKEN VARCHAR(100),
  IS_ACTIVE BOOLEAN
);

CREATE TABLE NODE(
  PROJECT VARCHAR(50),
  IP VARCHAR(50),
  OS VARCHAR(10) DEFAULT 'linux',
  IS_MASTER BOOLEAN,
  FOREIGN KEY (PROJECT) REFERENCES PROJECT(NAME),
  PRIMARY KEY (PROJECT, IP)
);
